# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/VGARAM/VGARAM.xci
# IP: The module: 'VGARAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/VGARAM/VGARAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGARAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/VGARAM/VGARAM.xci
# IP: The module: 'VGARAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/VGARAM/VGARAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGARAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
