# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.cache/wt [current_project]
set_property parent.project_path D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/test.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/D_snakeDEMO.coe
add_files D:/mowang/2025_1/Vivado/FullSingleCPU/testac.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/VGA/font_ascii_8_8.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/VGA/TestVGA.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/PWM/zztdd_8kHz_mono.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/migong.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/migong_1.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/migong_2.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/migong_3.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/test0.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/test1.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/test2.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/shuzuxianshi.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/xunhuanditu2.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/xunhuanxianshi_i_hanshu.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/test0_define_hanshu_anniu_jia.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/wu.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/you1.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/migong_4.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/gaidizhi.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/ceshuzu.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/yiweishuzu.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/yiweishuzu2.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/yiweishuzu3.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/ceshishuzu4.coe
add_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/xianshisuoyouditu.coe
add_files d:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/yaochenggongl.coe
read_verilog -library xil_defaultlib {
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/IO/Counter_3_IO.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/PCPU/ctrl_encode_def.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/PCPU/EXT.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/IO/Enter.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/PCPU/Forwarding_unit.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/PCPU/GRE_array.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/PCPU/Hazard_detecction_unit.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/MIO_BUS.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/edf_file_new/Multi_8CH32.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/PCPU/NPC.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/PCPU/PC.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/PCPU/PCPU.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/new/Pixel_control.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/PCPU/RF.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/edf_file_new/SPIO.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/edf_file_new/SSeg7.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/VGA/VGAIO.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/VGA/VGA_Scan.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/new/VRAMS_Controller.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/PCPU/alu.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/new/audio_controller.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/IO/clk_div.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/PCPU/ctrl.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/dm_controller.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/new/pwm_audio_100m.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/new/tone_generator.v
  D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/Top.v
}
read_ip -quiet D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/RAM_B/RAM_B.xci
set_property used_in_implementation false [get_files -all d:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/RAM_B/RAM_B_ooc.xdc]

read_ip -quiet D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/VGARAM/VGARAM.xci
set_property used_in_implementation false [get_files -all d:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/VGARAM/VGARAM_ooc.xdc]

read_ip -quiet D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet D:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/ROM_D/ROM_D.xci
set_property used_in_implementation false [get_files -all d:/mowang/2025_1/ComplexApplication/ComplexApplication/ComplexApplication.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc]

read_edif D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/edf_file_new/SPIO.edf
read_edif D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/edf_file_new/SSeg7.edf
read_edif D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/edf_file_new/Multi_8CH32.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/icf.xdc
set_property used_in_implementation false [get_files D:/mowang/2025_1/ComplexApplication/ComplexApplication/FullPipelineCPU.srcs/sources_1/icf.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
