# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/mowang/2025_1/Vivado/FullPipelineCPU/FullPipelineCPU.srcs/sources_1/icf.xdc

# IP: ip/RAM_B/RAM_B.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_B || ORIG_REF_NAME==RAM_B} -quiet] -quiet
